import { MigrationInterface, QueryRunner } from 'typeorm';

export class Migration1772086240296 implements MigrationInterface {
  name = 'Migration1772086240296';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "saved_post" DROP CONSTRAINT "FK_667736eef71e667998427203476"`,
    );
    await queryRunner.query(`ALTER TABLE "saved_post" DROP COLUMN "post_id"`);
    await queryRunner.query(
      `ALTER TABLE "saved_post" ADD "post_id" integer NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "likes" DROP CONSTRAINT "FK_741df9b9b72f328a6d6f63e79ff"`,
    );
    await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "post_id"`);
    await queryRunner.query(
      `ALTER TABLE "likes" ADD "post_id" integer NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "media" DROP CONSTRAINT "FK_20dc152fa567df67110b94d6f16"`,
    );
    await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "post_id"`);
    await queryRunner.query(
      `ALTER TABLE "media" ADD "post_id" integer NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "posts" DROP CONSTRAINT "FK_d8be760cd953c4a98137c5237a6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "posts" DROP CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e"`,
    );
    await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "posts" ADD "id" SERIAL NOT NULL`);
    await queryRunner.query(
      `ALTER TABLE "posts" ADD CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id")`,
    );
    await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "parent_id"`);
    await queryRunner.query(`ALTER TABLE "posts" ADD "parent_id" integer`);
    await queryRunner.query(
      `ALTER TABLE "saved_post" ADD CONSTRAINT "FK_667736eef71e667998427203476" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "likes" ADD CONSTRAINT "FK_741df9b9b72f328a6d6f63e79ff" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "media" ADD CONSTRAINT "FK_20dc152fa567df67110b94d6f16" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "posts" ADD CONSTRAINT "FK_d8be760cd953c4a98137c5237a6" FOREIGN KEY ("parent_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "posts" DROP CONSTRAINT "FK_d8be760cd953c4a98137c5237a6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "media" DROP CONSTRAINT "FK_20dc152fa567df67110b94d6f16"`,
    );
    await queryRunner.query(
      `ALTER TABLE "likes" DROP CONSTRAINT "FK_741df9b9b72f328a6d6f63e79ff"`,
    );
    await queryRunner.query(
      `ALTER TABLE "saved_post" DROP CONSTRAINT "FK_667736eef71e667998427203476"`,
    );
    await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "parent_id"`);
    await queryRunner.query(`ALTER TABLE "posts" ADD "parent_id" bigint`);
    await queryRunner.query(
      `ALTER TABLE "posts" DROP CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e"`,
    );
    await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "id"`);
    await queryRunner.query(
      `ALTER TABLE "posts" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "posts" ADD CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id")`,
    );
    await queryRunner.query(
      `ALTER TABLE "posts" ADD CONSTRAINT "FK_d8be760cd953c4a98137c5237a6" FOREIGN KEY ("parent_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "post_id"`);
    await queryRunner.query(
      `ALTER TABLE "media" ADD "post_id" bigint NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "media" ADD CONSTRAINT "FK_20dc152fa567df67110b94d6f16" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(`ALTER TABLE "likes" DROP COLUMN "post_id"`);
    await queryRunner.query(
      `ALTER TABLE "likes" ADD "post_id" bigint NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "likes" ADD CONSTRAINT "FK_741df9b9b72f328a6d6f63e79ff" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(`ALTER TABLE "saved_post" DROP COLUMN "post_id"`);
    await queryRunner.query(
      `ALTER TABLE "saved_post" ADD "post_id" bigint NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "saved_post" ADD CONSTRAINT "FK_667736eef71e667998427203476" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }
}
