export const CLIENTS = {
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
};
export const EVENTS = {
  POST_CREATED: 'POST_CREATED',
};
export const CMD = {
  GET_NOTIFICATION: 'GET_NOTIFICATION',
  MARK_AS_READ: 'MARK_AS_READ',
  MARK_ALL_AS_READ: 'MARK_ALL_AS_READ',
};

export const QUEUES = {
  NOTIFICATION_QUEUE: 'NOTIFICATION_QUEUE',
  MEDIA_QUEUE: 'MEDIA_QUEUE',
};
export const JOBS = {
  NEW_POST: 'NEW_POST',
  LIKE_POST: 'LIKE_POST',
  COMMENT_POST: 'COMMENT_POST',
  CREATE_MEDIA: 'CREATE_MEDIA',
};

export const GRAVITY = 1.8;
